[build]
  base = "BookQuoteClient"
  command = "npm ci && npm run build -- --configuration production"
  publish = "dist/book-quote-client/browser"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20.11.0"