services:
  - type: web
    name: bookquote-frontend
    buildCommand: npm install && npm run build -- --configuration production
    staticPublishPath: dist/book-quote-client/browser
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
